version: '3.8'
services:
  redis-test:
    image: redis:alpine
    ports:
      - "6380:6379"  # Different port for test environment
    command: redis-server --appendonly no --save ""  # Disable persistence for tests

  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - REDIS_URL=redis://redis-test:6379
      - JWT_SECRET=test-secret
      - JWT_REFRESH_SECRET=test-refresh-secret
    depends_on:
      - redis-test
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test 